[package]
name = "glengine"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glfw = "0.55.0"
glam = "0.27.0"
lazy_static = "1.4.0"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"

[lib]
crate-type = ["lib"]