[workspace]
resolver = "2"
members = ["glengine-mdl","glengine",  "game"]

[profile.release]
codegen-units = 1
lto = true
#opt-level = 3

[workspace.dependencies]
russimp = { version = "3.2.0", features = ["prebuilt"] }
image = "0.25.4"
