[package]
name = "glengine-mdl"
version = "0.1.0"
edition = "2021"

[dependencies]
russimp.workspace = true
image.workspace = true
bincode = "2.0.0-rc.3"

[build-dependencies]
#glengine = { path = "../"}

[lib]
crate-type = ["lib"]